name: montera
description: A memecoin tracker & trading app built on Solana (GMGN clone).
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  bip39: ^1.0.6
  crypto: ^3.0.3
  convert: ^3.1.1
  solana: ^0.30.2
  solana_wallet_provider: ^0.1.9
  fl_chart: ^0.65.0
  intl: ^0.18.1
  animations: ^2.0.11
  flutter_local_notifications: ^17.0.0
  url_launcher: ^6.2.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0
  qr_flutter: ^4.1.0
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  fluttertoast: ^8.2.4
  device_info_plus: ^9.1.0
  connectivity_plus: ^6.0.3
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  biometric_storage: ^5.0.0
  local_auth: ^2.2.0
  package_info_plus: ^5.0.1
  permission_handler: ^11.3.1
  dots_indicator: ^3.0.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - .env
