name: montera
description: Aplikasi crypto wallet Solana mirip GMGN
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^0.13.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  solana: ^0.29.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_local_notifications: ^17.0.0
  flutter_secure_storage: ^9.0.0
  charts_flutter: ^0.12.0
  candlesticks: ^0.2.1
  biometric_storage: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/